# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField(default=0)),
                ('productid', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('ct', models.IntegerField(default=0)),
                ('multiplier', models.IntegerField(default=1)),
                ('urgent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=10)),
                ('ipaddress', models.CharField(max_length=15)),
                ('queuemode', models.CharField(choices=[('B', 'Bag'), ('Q', 'Queue')], default='B', max_length=1)),
                ('ownership', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDataTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtime', models.DateTimeField(auto_now_add=True)),
                ('output', models.IntegerField(default=0)),
                ('mct', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_core.Jobs')),
            ],
        ),
    ]
